theme = "ayu_light_custom"

[editor]
line-number = "relative"
bufferline = "always"
color-modes = true
auto-format = true
scroll-lines = 1
true-color = true
idle-timeout = 50

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
separator = "󰘬"
left = [
  "mode",
  "spinner",
  "spacer",
  "separator",
  "spacer",
  "version-control",
  "spacer",
  "file-base-name",
  "file-type",
]
right = ["diagnostics", "workspace-diagnostics"]

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
C-s = ":w"
C-q = ":bc"
"=" = ":format"
C-w = { "|" = "vsplit", "minus" = "hsplit" }
space = { w = { "|" = "vsplit", "minus" = "hsplit" } }

[keys.insert]
C-s = ":w"

[keys.insert.j]
k = "normal_mode"
