theme = "dracula"

[editor]
line-number = "relative"
bufferline = "always"
color-modes = true
auto-format = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "version-control"]

[editor.indent-guides]
render = true

[keys.normal]
C-s = ":w"
C-q = ":q"
tab = ":buffer-next"
S-tab = ":buffer-previous"

[keys.insert]
C-s = ":w"
C-q = ":q"

[keys.insert.j]
k = "normal_mode"
