theme = "ayu_light_custom"

[editor]
line-number = "relative"
bufferline = "always"
color-modes = true
auto-format = true
auto-save = true
scroll-lines = 1
true-color = true
idle-timeout = 50
# rulers = [88]
undercurl = false

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
separator = "󰘬"
left = [
  "mode",
  "spinner",
  "spacer",
  "separator",
  "spacer",
  "version-control",
  "spacer",
  "file-name",
  "file-type",
]
right = ["diagnostics", "workspace-diagnostics", "total-line-numbers", "position-percentage"]

[editor.indent-guides]
render = true

[keys.normal]
"=" = ":format"
tab = ":bn"
S-tab = ":bp"

# Extending and unextending lines
X = ["extend_line_above"]
A-x = ["extend_line_below", "extend_visual_line_up", "extend_visual_line_up", "extend_to_line_bounds"]
A-X = ["extend_line_above", "extend_visual_line_down", "extend_visual_line_down", "extend_to_line_bounds"]

# Easy select register
C-r = "select_register"

# Navigate windows
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

C-a = "goto_line_start"
C-e = "goto_line_end"

[keys.normal.space]
space = "command_palette"

[keys.normal.space.w]
n = "vsplit"
d = "hsplit"

[keys.normal.space.c]
s = ":w"
S = ":wa"
q = ":bc"

[keys.insert]
# Escape insert mode
j = { j = "normal_mode" }

# Navigate in insert mode
C-p = "move_line_up"
C-n = "move_line_down"
C-e = "goto_line_end_newline"
C-a = "goto_line_start"
C-f = "move_char_right"
C-b = "move_char_left"

# Learn to use the above
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.select]
# Easy select register
C-r = "select_register"
