theme = "catppuccin_latte"

[editor]
line-number = "relative"
bufferline = "always"
color-modes = true
auto-format = true
scroll-lines = 1
true-color = true
idle-timeout = 50
rulers = [88]

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
separator = "󰘬"
left = [
  "mode",
  "spinner",
  "spacer",
  "separator",
  "spacer",
  "version-control",
  "spacer",
  "file-name",
  "file-type",
]
right = ["diagnostics", "workspace-diagnostics", "total-line-numbers", "position-percentage"]

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
"=" = ":format"

[keys.normal.space.w]
d = "vsplit"
n = "hsplit"

[keys.normal.space.c]
s = ":w"
S = ":w!"
q = ":bc"

[keys.insert.j]
k = "normal_mode"
