[[language]]
name = "lua"
auto-format = true

[[language]]
name = "python"
auto-format = true
roots = ["pyproject.toml"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {}

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "java"
indent = { tab-width = 2, unit = " " }
auto-format = true

[[language]]
name = "html"
auto-format = true

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = " " }
auto-format = true
# language-server = { command = "multi-lsp-proxy", args = [
#   "--config",
#   "~/.config/helix/multi-lsp-proxy/typescript-emmet.toml"
# ]}

[[language]]
name = "tsx"
indent = { tab-width = 4, unit = " " }
auto-format = true
# language-server = { command = "multi-lsp-proxy", args = [
#   "--config",
#   "~/.config/helix/multi-lsp-proxy/typescript-emmet.toml"
# ]}

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = " " }
auto-format = true

[[language]]
name = "jsx"
indent = { tab-width = 4, unit = " " }
auto-format = true

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "typst"
roots = []
comment-token = "//"
file-types = ["typ"]
indent = { tab-width = 2, unit = " " }
language-server = { command = "typst-lsp" }

[[grammar]]
name = "typst"
# source = { git = "https://github.com/SeniorMars/tree-sitter-typst", rev="2e66ef4b798a26f0b82144143711f3f7a9e8ea35" }
source = { git = "https://github.com/frozolotl/tree-sitter-typst", rev="af40989c1a2e724a9625cae412c17a60969280ca" }

[[language]]
name = "cpp"
auto-format = true
language-server = { command = "/usr/local/opt/llvm/bin/clangd", args = ["--clang-tidy", "--enable-config", "--inlay-hints"]}
